[workspace.package]
edition = "2021"
authors = ["Francesco Ceccon", "The Apibara contributors"]
repository = "https://github.com/apibara/dna"
license = "Apache-2.0"

[workspace]
resolver = "2"
members = [
    "observability",
    "etcd",
    "etcd-dbg",
    "protocol",
    "common",
    # "evm",
    # "starknet",
    "beaconchain",
]

[workspace.dependencies]
alloy-primitives = "0.7"
alloy-eips = "0.2.1"
# assert_matches = "1.5.0"
# anstyle = "1.0.1"
# arrayvec = "0.7.2"
# async-channel = "2.1.1"
# async-compression = { version = "0.4.6", features = ["tokio", "zstd"] }
# async-stream = "0.3.5"
# async-trait = "0.1.57"
# bytecheck = "0.6.12"
bytes = "1.7.1"
# byteorder = "1.4.3"
byte-unit = "5.1.4"
clap = { version = "4.5.13", features = [
    "derive",
    "env",
    "cargo",
    "unicode",
    "color",
    "unstable-styles",
] }
ctrlc = { version = "3.4.5", features = ["termination"] }
# deno_ast = { version = "0.31", features = ["cjs", "transpiling"] }
# deno_core = "0.224.0"
# deno_runtime = "0.130.0"
# dirs = "4.0.0"
# dotenvy = "0.15.7"
error-stack = "0.5.0"
etcd-client = { version = "0.14.0", features = ["tls", "tls-roots"] }
# flate2 = "1.0"
# flatbuffers = { version = "23.5.26", features = ["serialize"] }
futures = "0.3.30"
# futures-util = "0.3.26"
# governor = "0.6.0"
hex = { version = "0.4.3", features = ["serde"] }
# http = "0.2.9"
# hyper = "0.14.20"
# lazy_static = "1.4.0"
# lru = "0.12.3"
# jemallocator = { version = "0.5.0" }
# memmap2 = "0.9.4"
# mockall = "0.11.4"
# nanoid = "0.4.0"
opentelemetry = { version = "0.24.0", features = ["trace", "metrics"] }
opentelemetry_sdk = { version = "0.24.1", features = [
    "trace",
    "metrics",
    "rt-tokio",
] }
opentelemetry-otlp = { version = "0.17.0", features = [
    "trace",
    "metrics",
    "grpc-tonic",
] }
pin-project = "1.1.5"
prost = "0.13.1"
prost-types = "0.13.1"
reqwest = { version = "0.12.5", default-features = false, features = [
    "json",
    "rustls-tls",
] }
# regex = "1.9.1"
rkyv = { version = "0.8.0-rc.1" }
roaring = "0.10.6"
# rusqlite = "0.29.0"
serde = { version = "1.0.205", features = ["derive"] }
serde_json = "1.0.122"
serde_with = "3.9.0"
# thiserror = "1.0.32"
# tempfile = "3.3.0"
# tempdir = "0.3.7"
testcontainers = "0.22.0"
time = { version = "0.3.36", features = ["formatting", "local-offset"] }
tokio = { version = "1.39.2", features = ["full"] }
tokio-stream = { version = "0.1.15", features = ["sync", "net"] }
tokio-util = "0.7.11"
tonic = { version = "0.12.1", features = ["tls", "tls-roots", "prost"] }
tonic-build = "0.12.1"
# tonic-health = "0.9.0"
# tonic-reflection = "0.9.0"
# tower = "0.4.13"
tracing = { version = "0.1.40", features = [
    "max_level_trace",
    "release_max_level_debug",
] }
# tracing-futures = { version = "0.2.5", features = ["tokio", "futures-03"] }
tracing-opentelemetry = "0.25.0"
tracing-subscriber = { version = "0.3.18", features = [
    "std",
    "env-filter",
    "json",
] }
# tracing-tree = "0.2.2"
# quickcheck = "1.0.3"
# quickcheck_macros = "1.0.0"
# warp = "0.3.5"
# wiremock = "0.5.19"
url = "2.5"
