---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "operator.fullname" . }}-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - endpoints
  - configmaps
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  - pods/status
  - pods/finalizers
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - services
  - services/status
  - services/finalizers
  verbs:
  - "*"
- apiGroups:
  - "apibara.com"
  resources:
  - indexers
  - indexers/status
  - indexers/finalizers
  verbs:
  - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "operator.fullname" . }}-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "operator.fullname" . }}-role
subjects:
- kind: ServiceAccount
  name: {{ template "operator.serviceAccountName" . }}
  namespace: {{ template "operator.namespace" . }}
